version: "3"

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend/prisma:/app/prisma

    restart: always
